# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fdt_pindlg.ui'
#
# Created: Wed Jul 24 17:51:05 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PinDialog(object):
    def setupUi(self, PinDialog):
        PinDialog.setObjectName(_fromUtf8("PinDialog"))
        PinDialog.resize(328, 709)
        PinDialog.setMinimumSize(QtCore.QSize(280, 0))
        self.verticalLayout = QtGui.QVBoxLayout(PinDialog)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(PinDialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 316, 616))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setMargin(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.addPinGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.addPinGroupBox.setObjectName(_fromUtf8("addPinGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.addPinGroupBox)
        self.gridLayout.setMargin(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.addPinGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.pinSetByLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinSetByLineEdit.setObjectName(_fromUtf8("pinSetByLineEdit"))
        self.gridLayout.addWidget(self.pinSetByLineEdit, 8, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pinKindLabel = QtGui.QLabel(self.addPinGroupBox)
        self.pinKindLabel.setObjectName(_fromUtf8("pinKindLabel"))
        self.horizontalLayout_4.addWidget(self.pinKindLabel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.addPinGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.addPinGroupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.addPinGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.pinNameLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinNameLineEdit.setObjectName(_fromUtf8("pinNameLineEdit"))
        self.gridLayout.addWidget(self.pinNameLineEdit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.pinInfoTextEdit = QtGui.QPlainTextEdit(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pinInfoTextEdit.sizePolicy().hasHeightForWidth())
        self.pinInfoTextEdit.setSizePolicy(sizePolicy)
        self.pinInfoTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pinInfoTextEdit.setTabChangesFocus(True)
        self.pinInfoTextEdit.setObjectName(_fromUtf8("pinInfoTextEdit"))
        self.gridLayout.addWidget(self.pinInfoTextEdit, 7, 1, 1, 1)
        self.pinDateEdit = QtGui.QDateEdit(self.addPinGroupBox)
        self.pinDateEdit.setObjectName(_fromUtf8("pinDateEdit"))
        self.gridLayout.addWidget(self.pinDateEdit, 9, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pinElevDblSpnBx = QtGui.QDoubleSpinBox(self.addPinGroupBox)
        self.pinElevDblSpnBx.setDecimals(3)
        self.pinElevDblSpnBx.setMaximum(30000.0)
        self.pinElevDblSpnBx.setObjectName(_fromUtf8("pinElevDblSpnBx"))
        self.horizontalLayout_7.addWidget(self.pinElevDblSpnBx)
        self.pinElevUnitsCmbBx = QtGui.QComboBox(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinElevUnitsCmbBx.sizePolicy().hasHeightForWidth())
        self.pinElevUnitsCmbBx.setSizePolicy(sizePolicy)
        self.pinElevUnitsCmbBx.setObjectName(_fromUtf8("pinElevUnitsCmbBx"))
        self.pinElevUnitsCmbBx.addItem(_fromUtf8(""))
        self.pinElevUnitsCmbBx.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.pinElevUnitsCmbBx)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.addPinGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.frame = QtGui.QFrame(self.addPinGroupBox)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.pinXDblSpinBx = QtGui.QDoubleSpinBox(self.frame)
        self.pinXDblSpinBx.setDecimals(4)
        self.pinXDblSpinBx.setMaximum(10000000.0)
        self.pinXDblSpinBx.setObjectName(_fromUtf8("pinXDblSpinBx"))
        self.horizontalLayout.addWidget(self.pinXDblSpinBx)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.pinYDblSpinBx = QtGui.QDoubleSpinBox(self.frame)
        self.pinYDblSpinBx.setDecimals(4)
        self.pinYDblSpinBx.setMaximum(10000000.0)
        self.pinYDblSpinBx.setObjectName(_fromUtf8("pinYDblSpinBx"))
        self.horizontalLayout_2.addWidget(self.pinYDblSpinBx)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.fromOriginFrame = QtGui.QFrame(self.frame)
        self.fromOriginFrame.setObjectName(_fromUtf8("fromOriginFrame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.fromOriginFrame)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.fromOriginDistDblSpnBx = QtGui.QDoubleSpinBox(self.fromOriginFrame)
        self.fromOriginDistDblSpnBx.setDecimals(3)
        self.fromOriginDistDblSpnBx.setMaximum(999.99)
        self.fromOriginDistDblSpnBx.setObjectName(_fromUtf8("fromOriginDistDblSpnBx"))
        self.horizontalLayout_6.addWidget(self.fromOriginDistDblSpnBx)
        self.fromOriginUnitsCmbBx = QtGui.QComboBox(self.fromOriginFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromOriginUnitsCmbBx.sizePolicy().hasHeightForWidth())
        self.fromOriginUnitsCmbBx.setSizePolicy(sizePolicy)
        self.fromOriginUnitsCmbBx.setObjectName(_fromUtf8("fromOriginUnitsCmbBx"))
        self.fromOriginUnitsCmbBx.addItem(_fromUtf8(""))
        self.fromOriginUnitsCmbBx.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.fromOriginUnitsCmbBx)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 3)
        self.label_10 = QtGui.QLabel(self.fromOriginFrame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toNBtn = QtGui.QToolButton(self.fromOriginFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toNBtn.sizePolicy().hasHeightForWidth())
        self.toNBtn.setSizePolicy(sizePolicy)
        self.toNBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toNBtn.setObjectName(_fromUtf8("toNBtn"))
        self.gridLayout_2.addWidget(self.toNBtn, 0, 1, 1, 1)
        self.toOriginIconLabel = QtGui.QLabel(self.fromOriginFrame)
        self.toOriginIconLabel.setText(_fromUtf8(""))
        self.toOriginIconLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/fossildigtools/icons/origin.svg")))
        self.toOriginIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toOriginIconLabel.setObjectName(_fromUtf8("toOriginIconLabel"))
        self.gridLayout_2.addWidget(self.toOriginIconLabel, 1, 1, 1, 1)
        self.toEBtn = QtGui.QToolButton(self.fromOriginFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toEBtn.sizePolicy().hasHeightForWidth())
        self.toEBtn.setSizePolicy(sizePolicy)
        self.toEBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toEBtn.setObjectName(_fromUtf8("toEBtn"))
        self.gridLayout_2.addWidget(self.toEBtn, 1, 2, 1, 1)
        self.toWBtn = QtGui.QToolButton(self.fromOriginFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toWBtn.sizePolicy().hasHeightForWidth())
        self.toWBtn.setSizePolicy(sizePolicy)
        self.toWBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toWBtn.setObjectName(_fromUtf8("toWBtn"))
        self.gridLayout_2.addWidget(self.toWBtn, 1, 0, 1, 1)
        self.toSBtn = QtGui.QToolButton(self.fromOriginFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toSBtn.sizePolicy().hasHeightForWidth())
        self.toSBtn.setSizePolicy(sizePolicy)
        self.toSBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toSBtn.setObjectName(_fromUtf8("toSBtn"))
        self.gridLayout_2.addWidget(self.toSBtn, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.fromOriginFrame)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(66, 67, 253);"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.fromOriginFrame)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.capturePinBtn = QtGui.QToolButton(self.frame)
        self.capturePinBtn.setMinimumSize(QtCore.QSize(26, 26))
        self.capturePinBtn.setMaximumSize(QtCore.QSize(26, 26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/fossildigtools/icons/capturepin-origin.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capturePinBtn.setIcon(icon)
        self.capturePinBtn.setIconSize(QtCore.QSize(20, 20))
        self.capturePinBtn.setCheckable(True)
        self.capturePinBtn.setObjectName(_fromUtf8("capturePinBtn"))
        self.horizontalLayout_3.addWidget(self.capturePinBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.frame, 4, 1, 2, 1)
        self.pinOriginLabel = QtGui.QLabel(self.addPinGroupBox)
        self.pinOriginLabel.setObjectName(_fromUtf8("pinOriginLabel"))
        self.gridLayout.addWidget(self.pinOriginLabel, 2, 0, 1, 1)
        self.pinOriginLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinOriginLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: rgba(255, 255, 255, 128);}"))
        self.pinOriginLineEdit.setReadOnly(True)
        self.pinOriginLineEdit.setObjectName(_fromUtf8("pinOriginLineEdit"))
        self.gridLayout.addWidget(self.pinOriginLineEdit, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.addPinGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label_2 = QtGui.QLabel(PinDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(_fromUtf8("QLabel {font-size: 0.75em;}"))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.buttonBox = QtGui.QDialogButtonBox(PinDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PinDialog)
        QtCore.QMetaObject.connectSlotsByName(PinDialog)
        PinDialog.setTabOrder(self.pinNameLineEdit, self.pinXDblSpinBx)
        PinDialog.setTabOrder(self.pinXDblSpinBx, self.pinYDblSpinBx)
        PinDialog.setTabOrder(self.pinYDblSpinBx, self.pinInfoTextEdit)
        PinDialog.setTabOrder(self.pinInfoTextEdit, self.pinSetByLineEdit)
        PinDialog.setTabOrder(self.pinSetByLineEdit, self.buttonBox)

    def retranslateUi(self, PinDialog):
        PinDialog.setWindowTitle(_translate("PinDialog", "Location Pin", None))
        self.label_8.setText(_translate("PinDialog", "Kind", None))
        self.pinKindLabel.setText(_translate("PinDialog", "TextLabel", None))
        self.label_7.setText(_translate("PinDialog", "Set by", None))
        self.label_5.setText(_translate("PinDialog", "Info", None))
        self.label_6.setText(_translate("PinDialog", "Name", None))
        self.label_3.setText(_translate("PinDialog", "Coords", None))
        self.pinDateEdit.setDisplayFormat(_translate("PinDialog", "yyyy/MM/dd", None))
        self.pinElevUnitsCmbBx.setItemText(0, _translate("PinDialog", "ft", None))
        self.pinElevUnitsCmbBx.setItemText(1, _translate("PinDialog", "m", None))
        self.label_12.setText(_translate("PinDialog", "Elevation", None))
        self.label.setText(_translate("PinDialog", "X", None))
        self.label_4.setText(_translate("PinDialog", "Y", None))
        self.fromOriginUnitsCmbBx.setItemText(0, _translate("PinDialog", "ft", None))
        self.fromOriginUnitsCmbBx.setItemText(1, _translate("PinDialog", "m", None))
        self.label_10.setText(_translate("PinDialog", "Capture from origin", None))
        self.toNBtn.setText(_translate("PinDialog", "N", None))
        self.toEBtn.setText(_translate("PinDialog", "E", None))
        self.toWBtn.setText(_translate("PinDialog", "W", None))
        self.toSBtn.setText(_translate("PinDialog", "S", None))
        self.label_11.setText(_translate("PinDialog", "True", None))
        self.label_9.setText(_translate("PinDialog", "Capture from map", None))
        self.capturePinBtn.setText(_translate("PinDialog", "...", None))
        self.pinOriginLabel.setText(_translate("PinDialog", "Origin", None))
        self.label_2.setText(_translate("PinDialog", "Note: map projection and coordinates must be in UTM (meters)", None))

import resources_rc
