# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fdt_pindlg.ui'
#
# Created: Tue Aug  6 16:26:48 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PinDialog(object):
    def setupUi(self, PinDialog):
        PinDialog.setObjectName(_fromUtf8("PinDialog"))
        PinDialog.resize(367, 883)
        PinDialog.setMinimumSize(QtCore.QSize(320, 0))
        self.verticalLayout = QtGui.QVBoxLayout(PinDialog)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(PinDialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 355, 790))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setMargin(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.addPinGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.addPinGroupBox.setObjectName(_fromUtf8("addPinGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.addPinGroupBox)
        self.gridLayout.setMargin(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.addPinGroupBox)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.pinXDblSpinBx = QtGui.QDoubleSpinBox(self.frame)
        self.pinXDblSpinBx.setDecimals(4)
        self.pinXDblSpinBx.setMaximum(10000000.0)
        self.pinXDblSpinBx.setObjectName(_fromUtf8("pinXDblSpinBx"))
        self.horizontalLayout.addWidget(self.pinXDblSpinBx)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.pinYDblSpinBx = QtGui.QDoubleSpinBox(self.frame)
        self.pinYDblSpinBx.setDecimals(4)
        self.pinYDblSpinBx.setMaximum(10000000.0)
        self.pinYDblSpinBx.setObjectName(_fromUtf8("pinYDblSpinBx"))
        self.horizontalLayout_2.addWidget(self.pinYDblSpinBx)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.capturePinBtn = QtGui.QToolButton(self.frame)
        self.capturePinBtn.setMinimumSize(QtCore.QSize(26, 26))
        self.capturePinBtn.setMaximumSize(QtCore.QSize(26, 26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/fossildigtools/icons/capturepin-origin.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capturePinBtn.setIcon(icon)
        self.capturePinBtn.setIconSize(QtCore.QSize(20, 20))
        self.capturePinBtn.setCheckable(True)
        self.capturePinBtn.setObjectName(_fromUtf8("capturePinBtn"))
        self.horizontalLayout_3.addWidget(self.capturePinBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.calcFrame = QtGui.QFrame(self.frame)
        self.calcFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.calcFrame.setObjectName(_fromUtf8("calcFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.calcFrame)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_13 = QtGui.QLabel(self.calcFrame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.calcTabWidget = QtGui.QTabWidget(self.calcFrame)
        self.calcTabWidget.setStyleSheet(_fromUtf8("QTabWidget::pane {\n"
"  border-top: 1px inset #C2C7CB;\n"
"  position: absolute;\n"
"  padding-top: 6px;}"))
        self.calcTabWidget.setObjectName(_fromUtf8("calcTabWidget"))
        self.calcOrigin = QtGui.QWidget()
        self.calcOrigin.setObjectName(_fromUtf8("calcOrigin"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.calcOrigin)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.fromOriginDistDblSpnBx = QtGui.QDoubleSpinBox(self.calcOrigin)
        self.fromOriginDistDblSpnBx.setDecimals(3)
        self.fromOriginDistDblSpnBx.setMaximum(999.99)
        self.fromOriginDistDblSpnBx.setObjectName(_fromUtf8("fromOriginDistDblSpnBx"))
        self.horizontalLayout_6.addWidget(self.fromOriginDistDblSpnBx)
        self.fromOriginUnitsCmbBx = QtGui.QComboBox(self.calcOrigin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromOriginUnitsCmbBx.sizePolicy().hasHeightForWidth())
        self.fromOriginUnitsCmbBx.setSizePolicy(sizePolicy)
        self.fromOriginUnitsCmbBx.setObjectName(_fromUtf8("fromOriginUnitsCmbBx"))
        self.fromOriginUnitsCmbBx.addItem(_fromUtf8(""))
        self.fromOriginUnitsCmbBx.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.fromOriginUnitsCmbBx)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(3)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toNBtn = QtGui.QToolButton(self.calcOrigin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toNBtn.sizePolicy().hasHeightForWidth())
        self.toNBtn.setSizePolicy(sizePolicy)
        self.toNBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toNBtn.setObjectName(_fromUtf8("toNBtn"))
        self.gridLayout_2.addWidget(self.toNBtn, 0, 1, 1, 1)
        self.toOriginIconLabel = QtGui.QLabel(self.calcOrigin)
        self.toOriginIconLabel.setText(_fromUtf8(""))
        self.toOriginIconLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/fossildigtools/icons/origin.svg")))
        self.toOriginIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toOriginIconLabel.setObjectName(_fromUtf8("toOriginIconLabel"))
        self.gridLayout_2.addWidget(self.toOriginIconLabel, 1, 1, 1, 1)
        self.toEBtn = QtGui.QToolButton(self.calcOrigin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toEBtn.sizePolicy().hasHeightForWidth())
        self.toEBtn.setSizePolicy(sizePolicy)
        self.toEBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toEBtn.setObjectName(_fromUtf8("toEBtn"))
        self.gridLayout_2.addWidget(self.toEBtn, 1, 2, 1, 1)
        self.toWBtn = QtGui.QToolButton(self.calcOrigin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toWBtn.sizePolicy().hasHeightForWidth())
        self.toWBtn.setSizePolicy(sizePolicy)
        self.toWBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toWBtn.setObjectName(_fromUtf8("toWBtn"))
        self.gridLayout_2.addWidget(self.toWBtn, 1, 0, 1, 1)
        self.toSBtn = QtGui.QToolButton(self.calcOrigin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toSBtn.sizePolicy().hasHeightForWidth())
        self.toSBtn.setSizePolicy(sizePolicy)
        self.toSBtn.setMinimumSize(QtCore.QSize(24, 0))
        self.toSBtn.setObjectName(_fromUtf8("toSBtn"))
        self.gridLayout_2.addWidget(self.toSBtn, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.calcOrigin)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(66, 67, 253);"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.calcTabWidget.addTab(self.calcOrigin, _fromUtf8(""))
        self.calcAzimuth = QtGui.QWidget()
        self.calcAzimuth.setObjectName(_fromUtf8("calcAzimuth"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.calcAzimuth)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_10 = QtGui.QLabel(self.calcAzimuth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.azimuthFromCmbBx = QtGui.QComboBox(self.calcAzimuth)
        self.azimuthFromCmbBx.setObjectName(_fromUtf8("azimuthFromCmbBx"))
        self.gridLayout_3.addWidget(self.azimuthFromCmbBx, 0, 1, 1, 1)
        self.azimuthCapturePinBtn = QtGui.QToolButton(self.calcAzimuth)
        self.azimuthCapturePinBtn.setMinimumSize(QtCore.QSize(26, 26))
        self.azimuthCapturePinBtn.setMaximumSize(QtCore.QSize(26, 26))
        self.azimuthCapturePinBtn.setIcon(icon)
        self.azimuthCapturePinBtn.setIconSize(QtCore.QSize(20, 20))
        self.azimuthCapturePinBtn.setCheckable(True)
        self.azimuthCapturePinBtn.setObjectName(_fromUtf8("azimuthCapturePinBtn"))
        self.gridLayout_3.addWidget(self.azimuthCapturePinBtn, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.azimuthDblSpnBx = QtGui.QDoubleSpinBox(self.calcAzimuth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.azimuthDblSpnBx.sizePolicy().hasHeightForWidth())
        self.azimuthDblSpnBx.setSizePolicy(sizePolicy)
        self.azimuthDblSpnBx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.azimuthDblSpnBx.setDecimals(2)
        self.azimuthDblSpnBx.setMaximum(360.0)
        self.azimuthDblSpnBx.setObjectName(_fromUtf8("azimuthDblSpnBx"))
        self.horizontalLayout_8.addWidget(self.azimuthDblSpnBx)
        self.label_14 = QtGui.QLabel(self.calcAzimuth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.azimuthDistDblSpnBx = QtGui.QDoubleSpinBox(self.calcAzimuth)
        self.azimuthDistDblSpnBx.setDecimals(3)
        self.azimuthDistDblSpnBx.setMaximum(999.99)
        self.azimuthDistDblSpnBx.setObjectName(_fromUtf8("azimuthDistDblSpnBx"))
        self.horizontalLayout_8.addWidget(self.azimuthDistDblSpnBx)
        self.azimuthUnitsCmbBx = QtGui.QComboBox(self.calcAzimuth)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.azimuthUnitsCmbBx.sizePolicy().hasHeightForWidth())
        self.azimuthUnitsCmbBx.setSizePolicy(sizePolicy)
        self.azimuthUnitsCmbBx.setObjectName(_fromUtf8("azimuthUnitsCmbBx"))
        self.azimuthUnitsCmbBx.addItem(_fromUtf8(""))
        self.azimuthUnitsCmbBx.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.azimuthUnitsCmbBx)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.azimuthCorrectedChkBx = QtGui.QCheckBox(self.calcAzimuth)
        self.azimuthCorrectedChkBx.setObjectName(_fromUtf8("azimuthCorrectedChkBx"))
        self.verticalLayout_6.addWidget(self.azimuthCorrectedChkBx)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.calcTabWidget.addTab(self.calcAzimuth, _fromUtf8(""))
        self.calcOffset = QtGui.QWidget()
        self.calcOffset.setObjectName(_fromUtf8("calcOffset"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.calcOffset)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setVerticalSpacing(3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_15 = QtGui.QLabel(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.azimuthDistDblSpnBx_2 = QtGui.QDoubleSpinBox(self.calcOffset)
        self.azimuthDistDblSpnBx_2.setDecimals(3)
        self.azimuthDistDblSpnBx_2.setMaximum(999.99)
        self.azimuthDistDblSpnBx_2.setObjectName(_fromUtf8("azimuthDistDblSpnBx_2"))
        self.gridLayout_4.addWidget(self.azimuthDistDblSpnBx_2, 1, 1, 1, 1)
        self.azimuthFromCmbBx_2 = QtGui.QComboBox(self.calcOffset)
        self.azimuthFromCmbBx_2.setObjectName(_fromUtf8("azimuthFromCmbBx_2"))
        self.gridLayout_4.addWidget(self.azimuthFromCmbBx_2, 0, 1, 1, 2)
        self.azimuthUnitsCmbBx_2 = QtGui.QComboBox(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.azimuthUnitsCmbBx_2.sizePolicy().hasHeightForWidth())
        self.azimuthUnitsCmbBx_2.setSizePolicy(sizePolicy)
        self.azimuthUnitsCmbBx_2.setObjectName(_fromUtf8("azimuthUnitsCmbBx_2"))
        self.azimuthUnitsCmbBx_2.addItem(_fromUtf8(""))
        self.azimuthUnitsCmbBx_2.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.azimuthUnitsCmbBx_2, 1, 2, 1, 1)
        self.azimuthCapturePinBtn_2 = QtGui.QToolButton(self.calcOffset)
        self.azimuthCapturePinBtn_2.setMinimumSize(QtCore.QSize(26, 26))
        self.azimuthCapturePinBtn_2.setMaximumSize(QtCore.QSize(26, 26))
        self.azimuthCapturePinBtn_2.setIcon(icon)
        self.azimuthCapturePinBtn_2.setIconSize(QtCore.QSize(20, 20))
        self.azimuthCapturePinBtn_2.setCheckable(True)
        self.azimuthCapturePinBtn_2.setObjectName(_fromUtf8("azimuthCapturePinBtn_2"))
        self.gridLayout_4.addWidget(self.azimuthCapturePinBtn_2, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.azimuthUnitsCmbBx_3 = QtGui.QComboBox(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.azimuthUnitsCmbBx_3.sizePolicy().hasHeightForWidth())
        self.azimuthUnitsCmbBx_3.setSizePolicy(sizePolicy)
        self.azimuthUnitsCmbBx_3.setObjectName(_fromUtf8("azimuthUnitsCmbBx_3"))
        self.azimuthUnitsCmbBx_3.addItem(_fromUtf8(""))
        self.azimuthUnitsCmbBx_3.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.azimuthUnitsCmbBx_3, 1, 2, 1, 1)
        self.azimuthDistDblSpnBx_3 = QtGui.QDoubleSpinBox(self.calcOffset)
        self.azimuthDistDblSpnBx_3.setDecimals(3)
        self.azimuthDistDblSpnBx_3.setMaximum(999.99)
        self.azimuthDistDblSpnBx_3.setObjectName(_fromUtf8("azimuthDistDblSpnBx_3"))
        self.gridLayout_5.addWidget(self.azimuthDistDblSpnBx_3, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.azimuthCapturePinBtn_3 = QtGui.QToolButton(self.calcOffset)
        self.azimuthCapturePinBtn_3.setMinimumSize(QtCore.QSize(26, 26))
        self.azimuthCapturePinBtn_3.setMaximumSize(QtCore.QSize(26, 26))
        self.azimuthCapturePinBtn_3.setIcon(icon)
        self.azimuthCapturePinBtn_3.setIconSize(QtCore.QSize(20, 20))
        self.azimuthCapturePinBtn_3.setCheckable(True)
        self.azimuthCapturePinBtn_3.setObjectName(_fromUtf8("azimuthCapturePinBtn_3"))
        self.gridLayout_5.addWidget(self.azimuthCapturePinBtn_3, 0, 3, 1, 1)
        self.azimuthFromCmbBx_3 = QtGui.QComboBox(self.calcOffset)
        self.azimuthFromCmbBx_3.setObjectName(_fromUtf8("azimuthFromCmbBx_3"))
        self.gridLayout_5.addWidget(self.azimuthFromCmbBx_3, 0, 1, 1, 2)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_18 = QtGui.QLabel(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.calcOffset)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(5.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.01)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.comboBox = QtGui.QComboBox(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox)
        spacerItem3 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_17 = QtGui.QLabel(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.radioButton = QtGui.QRadioButton(self.calcOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_9.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.calcOffset)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_9.addWidget(self.radioButton_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.calcTabWidget.addTab(self.calcOffset, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.calcTabWidget)
        self.verticalLayout_2.addWidget(self.calcFrame)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 2)
        self.pinInfoTextEdit = QtGui.QPlainTextEdit(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pinInfoTextEdit.sizePolicy().hasHeightForWidth())
        self.pinInfoTextEdit.setSizePolicy(sizePolicy)
        self.pinInfoTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pinInfoTextEdit.setTabChangesFocus(True)
        self.pinInfoTextEdit.setObjectName(_fromUtf8("pinInfoTextEdit"))
        self.gridLayout.addWidget(self.pinInfoTextEdit, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.addPinGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.pinDateEdit = QtGui.QDateEdit(self.addPinGroupBox)
        self.pinDateEdit.setObjectName(_fromUtf8("pinDateEdit"))
        self.gridLayout.addWidget(self.pinDateEdit, 8, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.addPinGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pinKindLabel = QtGui.QLabel(self.addPinGroupBox)
        self.pinKindLabel.setObjectName(_fromUtf8("pinKindLabel"))
        self.horizontalLayout_4.addWidget(self.pinKindLabel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.addPinGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.pinSetByLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinSetByLineEdit.setObjectName(_fromUtf8("pinSetByLineEdit"))
        self.gridLayout.addWidget(self.pinSetByLineEdit, 7, 1, 1, 1)
        self.pinNameLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinNameLineEdit.setObjectName(_fromUtf8("pinNameLineEdit"))
        self.gridLayout.addWidget(self.pinNameLineEdit, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pinElevDblSpnBx = QtGui.QDoubleSpinBox(self.addPinGroupBox)
        self.pinElevDblSpnBx.setDecimals(3)
        self.pinElevDblSpnBx.setMaximum(30000.0)
        self.pinElevDblSpnBx.setObjectName(_fromUtf8("pinElevDblSpnBx"))
        self.horizontalLayout_7.addWidget(self.pinElevDblSpnBx)
        self.pinElevUnitsCmbBx = QtGui.QComboBox(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinElevUnitsCmbBx.sizePolicy().hasHeightForWidth())
        self.pinElevUnitsCmbBx.setSizePolicy(sizePolicy)
        self.pinElevUnitsCmbBx.setObjectName(_fromUtf8("pinElevUnitsCmbBx"))
        self.pinElevUnitsCmbBx.addItem(_fromUtf8(""))
        self.pinElevUnitsCmbBx.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.pinElevUnitsCmbBx)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.addPinGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.addPinGroupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.addPinGroupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.pinOriginLabel = QtGui.QLabel(self.addPinGroupBox)
        self.pinOriginLabel.setObjectName(_fromUtf8("pinOriginLabel"))
        self.gridLayout.addWidget(self.pinOriginLabel, 2, 0, 1, 1)
        self.pinOriginLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinOriginLineEdit.setStyleSheet(_fromUtf8("QLineEdit {background-color: rgba(255, 255, 255, 128);}"))
        self.pinOriginLineEdit.setReadOnly(True)
        self.pinOriginLineEdit.setObjectName(_fromUtf8("pinOriginLineEdit"))
        self.gridLayout.addWidget(self.pinOriginLineEdit, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.addPinGroupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label_2 = QtGui.QLabel(PinDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(_fromUtf8("QLabel {font-size: 0.75em;}"))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.buttonBox = QtGui.QDialogButtonBox(PinDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PinDialog)
        self.calcTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PinDialog)
        PinDialog.setTabOrder(self.pinNameLineEdit, self.pinXDblSpinBx)
        PinDialog.setTabOrder(self.pinXDblSpinBx, self.pinYDblSpinBx)
        PinDialog.setTabOrder(self.pinYDblSpinBx, self.pinInfoTextEdit)
        PinDialog.setTabOrder(self.pinInfoTextEdit, self.pinSetByLineEdit)
        PinDialog.setTabOrder(self.pinSetByLineEdit, self.buttonBox)

    def retranslateUi(self, PinDialog):
        PinDialog.setWindowTitle(_translate("PinDialog", "Location Pin", None))
        self.label.setText(_translate("PinDialog", "X", None))
        self.label_4.setText(_translate("PinDialog", "Y", None))
        self.label_9.setText(_translate("PinDialog", "Capture from map", None))
        self.capturePinBtn.setText(_translate("PinDialog", "...", None))
        self.label_13.setText(_translate("PinDialog", "Calculate from", None))
        self.fromOriginUnitsCmbBx.setItemText(0, _translate("PinDialog", "ft", None))
        self.fromOriginUnitsCmbBx.setItemText(1, _translate("PinDialog", "m", None))
        self.toNBtn.setText(_translate("PinDialog", "N", None))
        self.toEBtn.setText(_translate("PinDialog", "E", None))
        self.toWBtn.setText(_translate("PinDialog", "W", None))
        self.toSBtn.setText(_translate("PinDialog", "S", None))
        self.label_11.setText(_translate("PinDialog", "True", None))
        self.calcTabWidget.setTabText(self.calcTabWidget.indexOf(self.calcOrigin), _translate("PinDialog", "Orign", None))
        self.label_10.setText(_translate("PinDialog", "From", None))
        self.azimuthCapturePinBtn.setText(_translate("PinDialog", "...", None))
        self.azimuthDblSpnBx.setSuffix(_translate("PinDialog", "˚", None))
        self.label_14.setText(_translate("PinDialog", "@", None))
        self.azimuthUnitsCmbBx.setItemText(0, _translate("PinDialog", "ft", None))
        self.azimuthUnitsCmbBx.setItemText(1, _translate("PinDialog", "m", None))
        self.azimuthCorrectedChkBx.setText(_translate("PinDialog", "Azimuth corrected for declination", None))
        self.calcTabWidget.setTabText(self.calcTabWidget.indexOf(self.calcAzimuth), _translate("PinDialog", "Azimuth", None))
        self.label_15.setText(_translate("PinDialog", "From A", None))
        self.azimuthUnitsCmbBx_2.setItemText(0, _translate("PinDialog", "ft", None))
        self.azimuthUnitsCmbBx_2.setItemText(1, _translate("PinDialog", "m", None))
        self.azimuthCapturePinBtn_2.setText(_translate("PinDialog", "...", None))
        self.azimuthUnitsCmbBx_3.setItemText(0, _translate("PinDialog", "ft", None))
        self.azimuthUnitsCmbBx_3.setItemText(1, _translate("PinDialog", "m", None))
        self.label_16.setText(_translate("PinDialog", "From B", None))
        self.azimuthCapturePinBtn_3.setText(_translate("PinDialog", "...", None))
        self.label_18.setText(_translate("PinDialog", "+/-", None))
        self.comboBox.setItemText(0, _translate("PinDialog", "ft", None))
        self.comboBox.setItemText(1, _translate("PinDialog", "m", None))
        self.label_17.setText(_translate("PinDialog", "Line A-to-B, offset is ", None))
        self.radioButton.setText(_translate("PinDialog", "L", None))
        self.radioButton_2.setText(_translate("PinDialog", "R", None))
        self.calcTabWidget.setTabText(self.calcTabWidget.indexOf(self.calcOffset), _translate("PinDialog", "Offset", None))
        self.label_6.setText(_translate("PinDialog", "Name", None))
        self.pinDateEdit.setDisplayFormat(_translate("PinDialog", "yyyy/MM/dd", None))
        self.label_8.setText(_translate("PinDialog", "Kind", None))
        self.pinKindLabel.setText(_translate("PinDialog", "TextLabel", None))
        self.label_7.setText(_translate("PinDialog", "Set by", None))
        self.pinElevUnitsCmbBx.setItemText(0, _translate("PinDialog", "ft", None))
        self.pinElevUnitsCmbBx.setItemText(1, _translate("PinDialog", "m", None))
        self.label_12.setText(_translate("PinDialog", "Elevation", None))
        self.label_3.setText(_translate("PinDialog", "Coordinates", None))
        self.label_5.setText(_translate("PinDialog", "Info", None))
        self.pinOriginLabel.setText(_translate("PinDialog", "Origin", None))
        self.label_2.setText(_translate("PinDialog", "Note: map projection and coordinates must be in UTM (meters)", None))

import resources_rc
