# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fdt_pindlg.ui'
#
# Created: Tue Jul 16 14:31:54 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PinDialog(object):
    def setupUi(self, PinDialog):
        PinDialog.setObjectName(_fromUtf8("PinDialog"))
        PinDialog.resize(259, 467)
        self.verticalLayout = QtGui.QVBoxLayout(PinDialog)
        self.verticalLayout.setMargin(12)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addPinGroupBox = QtGui.QGroupBox(PinDialog)
        self.addPinGroupBox.setObjectName(_fromUtf8("addPinGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.addPinGroupBox)
        self.gridLayout.setMargin(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.addPinGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.addPinGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.addPinGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.addPinGroupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pinKindLabel = QtGui.QLabel(self.addPinGroupBox)
        self.pinKindLabel.setObjectName(_fromUtf8("pinKindLabel"))
        self.horizontalLayout_4.addWidget(self.pinKindLabel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.capturePinBtn = QtGui.QToolButton(self.addPinGroupBox)
        self.capturePinBtn.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/fossildigtools/icons/capturepin-origin.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capturePinBtn.setIcon(icon)
        self.capturePinBtn.setIconSize(QtCore.QSize(20, 20))
        self.capturePinBtn.setCheckable(True)
        self.capturePinBtn.setObjectName(_fromUtf8("capturePinBtn"))
        self.horizontalLayout_3.addWidget(self.capturePinBtn)
        self.label_9 = QtGui.QLabel(self.addPinGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pinXDblSpinBx = QtGui.QDoubleSpinBox(self.addPinGroupBox)
        self.pinXDblSpinBx.setDecimals(4)
        self.pinXDblSpinBx.setMaximum(10000000.0)
        self.pinXDblSpinBx.setObjectName(_fromUtf8("pinXDblSpinBx"))
        self.horizontalLayout.addWidget(self.pinXDblSpinBx)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pinYDblSpinBx = QtGui.QDoubleSpinBox(self.addPinGroupBox)
        self.pinYDblSpinBx.setDecimals(4)
        self.pinYDblSpinBx.setMaximum(10000000.0)
        self.pinYDblSpinBx.setObjectName(_fromUtf8("pinYDblSpinBx"))
        self.horizontalLayout_2.addWidget(self.pinYDblSpinBx)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.pinSetByLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinSetByLineEdit.setObjectName(_fromUtf8("pinSetByLineEdit"))
        self.gridLayout.addWidget(self.pinSetByLineEdit, 8, 1, 1, 1)
        self.pinNameLineEdit = QtGui.QLineEdit(self.addPinGroupBox)
        self.pinNameLineEdit.setObjectName(_fromUtf8("pinNameLineEdit"))
        self.gridLayout.addWidget(self.pinNameLineEdit, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.pinInfoTextEdit = QtGui.QPlainTextEdit(self.addPinGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pinInfoTextEdit.sizePolicy().hasHeightForWidth())
        self.pinInfoTextEdit.setSizePolicy(sizePolicy)
        self.pinInfoTextEdit.setTabChangesFocus(True)
        self.pinInfoTextEdit.setObjectName(_fromUtf8("pinInfoTextEdit"))
        self.gridLayout.addWidget(self.pinInfoTextEdit, 7, 1, 1, 1)
        self.pinOriginFrame = QtGui.QFrame(self.addPinGroupBox)
        self.pinOriginFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.pinOriginFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.pinOriginFrame.setObjectName(_fromUtf8("pinOriginFrame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.pinOriginFrame)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_13 = QtGui.QLabel(self.pinOriginFrame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.pinOriginLineEdit = QtGui.QLineEdit(self.pinOriginFrame)
        self.pinOriginLineEdit.setReadOnly(True)
        self.pinOriginLineEdit.setObjectName(_fromUtf8("pinOriginLineEdit"))
        self.horizontalLayout_5.addWidget(self.pinOriginLineEdit)
        self.gridLayout.addWidget(self.pinOriginFrame, 2, 1, 1, 1)
        self.pinDateEdit = QtGui.QDateEdit(self.addPinGroupBox)
        self.pinDateEdit.setObjectName(_fromUtf8("pinDateEdit"))
        self.gridLayout.addWidget(self.pinDateEdit, 9, 1, 1, 1)
        self.verticalLayout.addWidget(self.addPinGroupBox)
        self.label_2 = QtGui.QLabel(PinDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(_fromUtf8("QLabel {font-size: 0.75em;}"))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.buttonBox = QtGui.QDialogButtonBox(PinDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PinDialog)
        QtCore.QMetaObject.connectSlotsByName(PinDialog)
        PinDialog.setTabOrder(self.pinNameLineEdit, self.pinXDblSpinBx)
        PinDialog.setTabOrder(self.pinXDblSpinBx, self.pinYDblSpinBx)
        PinDialog.setTabOrder(self.pinYDblSpinBx, self.pinInfoTextEdit)
        PinDialog.setTabOrder(self.pinInfoTextEdit, self.pinSetByLineEdit)
        PinDialog.setTabOrder(self.pinSetByLineEdit, self.buttonBox)
        PinDialog.setTabOrder(self.buttonBox, self.capturePinBtn)
        PinDialog.setTabOrder(self.capturePinBtn, self.pinOriginLineEdit)

    def retranslateUi(self, PinDialog):
        PinDialog.setWindowTitle(_translate("PinDialog", "Location Pin", None))
        self.label_8.setText(_translate("PinDialog", "Kind", None))
        self.label_7.setText(_translate("PinDialog", "Set by", None))
        self.label_6.setText(_translate("PinDialog", "Name", None))
        self.label_5.setText(_translate("PinDialog", "Info", None))
        self.pinKindLabel.setText(_translate("PinDialog", "TextLabel", None))
        self.label_3.setText(_translate("PinDialog", "X coord", None))
        self.capturePinBtn.setText(_translate("PinDialog", "...", None))
        self.label_9.setText(_translate("PinDialog", "Capture from map", None))
        self.label_4.setText(_translate("PinDialog", "Y coord", None))
        self.label_13.setText(_translate("PinDialog", "Origin", None))
        self.pinDateEdit.setDisplayFormat(_translate("PinDialog", "yyyy/MM/dd", None))
        self.label_2.setText(_translate("PinDialog", "Note: map projection and coordinates must be in UTM (meters)", None))

import resources_rc
